version: '3.8'

services:
    php:
        build:
            context: docker/php
        image: php:8.3-fpm
        container_name: php8.3-dev
        ports:
            - "9000:9000"
        volumes:
            - "./:/var/www/html"
        restart: always
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx-dev
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        restart: always
        depends_on:
            - php
        networks:
            - app-network
    mysql:
        image: mysql:latest
        container_name: mysql-dev
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testing
        ports:
            - "3306:3306"
        depends_on:
            - php
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:

networks:
    app-network:
        driver: bridge
